"""initial_schema

Revision ID: 3e85de13ac0b
Revises: 
Create Date: 2026-03-05 11:54:59.513083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e85de13ac0b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('related_entity_type', sa.String(), nullable=True))
    op.add_column('notifications', sa.Column('related_entity_id', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'created_at')
    op.drop_column('notifications', 'related_entity_id')
    op.drop_column('notifications', 'related_entity_type')
    # ### end Alembic commands ###
